[package]
org = "roland"
name = "asb_message_to_twilio"
version = "0.1.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "asb"
version = "0.1.1"

[[dependency]]
org = "ballerinax"
name = "twilio"
version = "0.99.6"
