[package]
org = "roland"
name = "calendar_new_event_to_twilio_sms_gmail_email_via_asb"
version = "0.1.2"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "asb"
version = "0.1.3"

[[dependency]]
org = "ballerinax"
name = "twilio"
version = "0.99.7"

[[dependency]]
org = "ballerinax"
name = "googleapis_gmail"
version = "0.99.6"
