[package]
org = "roland"
name = "calendar_new_event_to_asb_new_message"
version = "0.1.2"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "asb"
version = "0.1.3"

[[dependency]]
org = "ballerinax"
name = "googleapis.calendar"
version = "0.1.5"