[[dependency]]
org = "ballerina"
name = "time"
version = "2.0.0-alpha8"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha7"

[[dependency]]
org = "ballerina"
name = "os"
version = "0.8.0-alpha7"

[[dependency]]
org = "ballerina"
name = "url"
version = "1.1.0-alpha7"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "1.1.0-alpha7"

[[dependency]]
org = "ballerina"
name = "auth"
version = "1.1.0-alpha7"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha7"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha7"

[[dependency]]
org = "ballerina"
name = "mime"
version = "1.1.0-alpha7"

[[dependency]]
org = "ballerinax"
name = "asb"
version = "0.1.3"

[[dependency]]
org = "ballerinax"
name = "twilio"
version = "0.99.7"

[[dependency]]
org = "ballerinax"
name = "googleapis_calendar"
version = "0.1.4"


