[package]
org = "roland"
name = "asb_message_to_new_gsheet_row"
version = "0.1.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "asb"
version = "0.1.3"

[[dependency]]
org = "ballerinax"
name = "googleapis.sheets"
version = "0.99.8"
